<?php
/**
 * ShipmentDate
 *
 * @category   IllApps
 * @package    IllApps_ShipmentDate
 * @author     Jonathan Cantrell (j@kernelhack.com)
 * @copyright  Copyright (c) 2011 EcoMATICS, Inc. DBA IllApps (http://www.illapps.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 */
?>

<div class="sp-methods-holder">
	<dl class="sp-methods" id="instore_selector">
	    <dt>Please Select One:</dt>
	    <dd>
	        <ul>
	            <li><input id="pickup_method_instore_no" name="instore_pickup" class="radio" type="radio" value="0" onChange="updateDeliveryMethod(this)" checked>
	            <label for="pickup_method_delivery" class="goleft"><?php echo $this->getOptionTitle('delivery')?></label></li>
	            <li><input id="pickup_method_instore_yes" name="instore_pickup" class="radio" type="radio" value="1" onChange="updateDeliveryMethod(this)" >
	            <label for="pickup_method_instore" class="goleft"><?php echo $this->getOptionTitle('instore')?></label></li>
	        </ul>
	    </dd>
	</dl>
	<input id="instore_value" name="instore_value" type="hidden" value="0" />
	<input id="date_update" name="date_update" type="hidden" value="" type="hidden" />
</div>