<?php

/**
 * ShipSync
 *
 * @category   IllApps
 * @package    IllApps_Shipsync
 * @author     David Kirby (d@kernelhack.com), Jonathan Cantrell (j@kernelhack.com)
 * @copyright  Copyright (c) 2011 EcoMATICS, Inc. DBA IllApps (http://www.illapps.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>

<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>Illapps/Shipsync/backend.js"></script>
<script type="text/javascript">var attributeurl = '<?php echo $this->getUrl('*/*/attributes') ?>'</script>
<script type="text/javascript">var optionsurl = '<?php echo $this->getUrl('*/*/options') ?>'</script>
<?php $rateUrl =  $this->getUrl('*/*/rate'); ?>
<?php $_order = $this->getOrder(); ?>
<div style="visibility: visible;" class="content-header">
    <h3 class="icon-head head-sales-order-shipment">New Shipment for Order #<?php echo $_order->getIncrementId(); ?></h3>
</div>
<form id="edit_form" name="edit_form" method="post" action="<?php echo $this->getUrl('*/*/post'); ?>">
    <input id="form_key" name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
    <input id="order_id" name="order_id" value="<?php echo $_order->getIncrementId(); ?>" type="hidden" />
    <input id="weight_units" name="weight_units" value="<?php echo $this->getWeightUnits(); ?>" type="hidden" />
    <input id="dimension_units" name="dimension_units" value="<?php echo $this->getDimensionUnits(); ?>" type="hidden" />
    <div class="box-left">
	<!--Order Information-->
	<?php $orderAdminDate = $this->formatDate($_order->getCreatedAtDate(), 'medium', true); ?>
	<?php $orderStoreDate = $this->formatDate($_order->getCreatedAtStoreDate(), 'medium', true); ?>
	<div class="entry-edit">
	    <?php if ($_order->getEmailSent()):
		$_email = Mage::helper('sales')->__('the order confirmation email was sent');
	    else:
		$_email = Mage::helper('sales')->__('the order confirmation email is not sent');
	    endif; ?>
	    <div style="" class="entry-edit-head">
		<a href="<?php echo $this->getOrderUrl(); ?>"><?php echo Mage::helper('sales')->__('Order # %s', $_order->getRealOrderId()) ?></a>
		<strong>(<?php echo $_email ?>)</strong>
	    </div>
	    <div class="fieldset">
		<table cellspacing="0" class="form-list">
		<tr>
		    <td class="label"><label><?php echo Mage::helper('sales')->__('Order Date') ?></label></td>
		    <td><strong><?php echo $orderAdminDate ?></strong></td>
		</tr>
		<?php if ($orderAdminDate != $orderStoreDate):?>
		<tr>
		    <td class="label"><label><?php echo Mage::helper('sales')->__('Order Date (%s)', $_order->getCreatedAtStoreDate()->getTimezone()) ?></label></td>
		    <td><strong><?php echo $orderStoreDate ?></strong></td>
		</tr>
		<?php endif;?>
		<tr>
		    <td class="label"><label><?php echo Mage::helper('sales')->__('Order Status') ?></label></td>
		    <td><strong><span id="order_status"><?php echo $_order->getStatusLabel() ?></span></strong></td>
		</tr>
		<tr>
		    <td class="label"><label><?php echo Mage::helper('sales')->__('Purchased From') ?></label></td>
		    <td><strong><?php echo nl2br($_order->getStoreName()); ?></strong></td>
		</tr>
		<?php if($_order->getRemoteIp()): ?>
		<tr>
		    <td class="label"><label><?php echo Mage::helper('sales')->__('Placed from IP') ?></label></td>
		    <td><strong><?php echo $_order->getRemoteIp(); echo ($_order->getXForwardedFor())?' (' . $_order->getXForwardedFor() . ')':''; ?></strong></td>
		</tr>
		<?php endif; ?>
		<?php if($_order->getGlobalCurrencyCode() != $_order->getBaseCurrencyCode()): ?>
		<tr>
		    <td class="label"><label><?php echo Mage::helper('sales')->__('%s / %s rate:', $_order->getGlobalCurrencyCode(), $_order->getBaseCurrencyCode()) ?></label></td>
		    <td><strong><?php echo $_order->getBaseToGlobalRate() ?></strong></td>
		</tr>
		<?php endif; ?>
		<?php if($_order->getBaseCurrencyCode() != $_order->getOrderCurrencyCode()): ?>
		<tr>
		    <td class="label"><label><?php echo Mage::helper('sales')->__('%s / %s rate:', $_order->getOrderCurrencyCode(), $_order->getBaseCurrencyCode()) ?></label></td>
		    <td><strong><?php echo $_order->getBaseToOrderRate() ?></strong></td>
		</tr>
		<?php endif; ?>
		<tr>
                    <td class="label"><label><?php echo Mage::helper('sales')->__('Carrier') ?></label></td>
                    <td><strong><?php echo $this->getCarrierTitle(); ?></strong></td>
                </tr>
		<tr>
                    <td class="label"><label><?php echo Mage::helper('sales')->__('Shipping Method') ?></label></td>
                    <td><strong><select id="method" name="method">
                        <?php foreach ($this->getAllowedMethods() as $method) { ?>
                            <?php echo '<option value="' . $method . '"'; if ($method == $this->getMethodCode()) echo " SELECTED";
                                  echo '>' . $this->getCarrier()->getCode('method', $method) . '</option>'; ?>
                        <?php } ?>
                        </select></strong>
                    </td>
                </tr>
		<tr>
		    <td class="label"><label><?php echo Mage::helper('sales')->__('Shipping Amount') ?></label></td>
		    <td><div style="font-weight:bold;"id="shipping_amount_div"><?php echo Mage::helper('core')->currency($_order->getShippingAmount()); ?></div></td>
		</tr>
                <tr>
                    <td class="label"><label>COD</label></td>
                    <td><input type="checkbox" name='cod' /></td>
                </tr>
		<tr>
		    <td class="label"><label>COD Collection Amount</label></td>
		    <td><input class="input-text" name="cod_amount" value="" /></td>
		</tr>
		<tr>
		    <td class="label"><label>Insure Amount</label></td>
		    <td><input class="input-text" name='insure_amount' value='<?php echo number_format($_order->getSubtotal(),2); ?>' /></td>
		</tr>
		<tr>
		    <td class="label"><label>Insure Shipment</label></td>
		    <td><input type="checkbox" name='insure_shipment' /></td>
		</tr>
		<tr>
		    <td class="label"><label>Require Signature</label></td>
		    <td><input type="checkbox" name='require_signature' /></td>
		</tr>
		<tr>
			<td class="label"><label><?php echo Mage::helper('sales')->__('Customer Name') ?></label></td>
			<td>
			<?php if ($_customerUrl=$this->getCustomerViewUrl()) : ?>
			    <a href="<?php echo $_customerUrl ?>" target="_blank"><strong><?php echo $this->htmlEscape($_order->getCustomerName()) ?></strong></a>
			<?php else: ?>
			    <strong><?php echo $this->htmlEscape($_order->getCustomerName()) ?></strong>
			<?php endif; ?>
			</td>
		    </tr>
		    <tr>
			<td class="label"><label><?php echo Mage::helper('sales')->__('Email') ?></label></td>
			<td><a href="mailto:<?php echo $_order->getCustomerEmail() ?>"><strong><?php echo $_order->getCustomerEmail() ?></strong></a></td>
		    </tr>
		    <?php if ($_groupName=$this->getCustomerGroupName()) : ?>
		    <tr>
			<td class="label"><label><?php echo Mage::helper('sales')->__('Customer Group') ?></label></td>
			<td><strong><?php echo $_groupName ?></strong></td>
                    </tr>
		    <?php endif; ?>
                    <tr>
                        <td class="label"><label>Send Shipment Confirmation</label></td>
                        <td valign="bottom"><input type="checkbox" id="confirmation" name="confirmation" checked></td>
                    </tr>
		    <?php if ($_dob=$this->getOrder()->getCustomerDob()) : ?>
		    <tr>
			<td class="label"><label><?php echo Mage::helper('sales')->__('Date of Birth') ?></label></td>
			<td><strong><?php echo Mage::helper('core')->formatDate($_dob, 'medium') ?></strong></td>
		    </tr>
		    <?php endif; ?>
		    <?php if ($_taxvat = $_order->getCustomerTaxvat()):?>
		    <tr>
			<td class="label"><label><?php echo Mage::helper('sales')->__('TAX/VAT Number') ?></label></td>
			<td><strong><?php echo $this->htmlEscape($_taxvat)?></strong></td>
		    </tr>
		    <?php endif;?>
		</table>
	    </div>
	</div>
    </div>

<div class="box-right">
    <!--Shipping Address-->
    <?php $shippingAddress = $_order->getShippingAddress(); ?>
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-shipping-address"><?php echo Mage::helper('sales')->__('Shipping Address') ?></h4>
        </div>
        <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
		    <tr>
			<td class="label"><label>Name</label></td>
			<td><input class="input-text required-entry" id="recipient_name" name="recipient_name" value="<?php echo $shippingAddress->getName(); ?>" /></td>
		    </tr>
		    <tr>
			<td class="label"><label>Company</label></td>
			<td><input class="input-text" id="recipient_company" name="recipient_company" value="<?php echo $shippingAddress->getCompany(); ?>" /></td>
		    </tr>
		    <tr>
			<td class="label"><label>Address</label></td>
			<td><input class="input-text required-entry" size="45" id="recipient_street1" name="recipient_street1" value="<?php echo $shippingAddress->getStreet1(); ?>" /></td>
		    </tr>
		    <tr>
			<td class="label"><label>Address (2)</label></td>
			<td><input class="input-text" size="45" id="recipient_street2" name="recipient_street2" value="<?php echo $shippingAddress->getStreet2(); ?>" /></td>
		    </tr>
		    <tr>
			<td class="label"><label>Address (3)</label></td>
			<td><input class="input-text" size="45" id="recipient_street3" name="recipient_street3" value="<?php echo $shippingAddress->getStreet3(); ?>" /></td>
		    </tr>
		    <tr>
			<td class="label"><label>City</label></td>
			<td><input class="input-text required-entry" id="recipient_city" name="recipient_city" value="<?php echo $shippingAddress->getCity(); ?>" /></td>
		    </tr>
		    <tr>
			<td class="label"><label>State/Region</label></td>
			<td><input class="input-text" id="recipient_region" name="recipient_region" value="<?php
			    if ($shippingAddress->getRegionCode() == '') { echo $shippingAddress->getRegion(); } else { echo $shippingAddress->getRegionCode(); } ?>" /></td>
		    </tr>
		    <tr>
			<td class="label"><label>Postal Code</label></td>
			<td><input class="input-text" size="9" id="recipient_postcode" name="recipient_postcode" value="<?php echo $shippingAddress->getPostcode(); ?>" /></td>
		    </tr>
		    <tr>
			<td class="label"><label>Country</label></td>
			<td><input class="input-text required-entry" id="recipient_country" name="recipient_country" value="<?php echo $shippingAddress->getCountry(); ?>" /></td>
		    </tr>
		    <tr>
			<td class="label"><label>Telephone</label></td>
			<td><input class="input-text required-entry" id="recipient_telephone" name="recipient_telephone" value="<?php echo $shippingAddress->getTelephone(); ?>" /></td>
		    </tr>
		</table>
	    </div>
	</div>
    </div>
</div>

<div class="clear"></div>

<div class="entry-edit-head">
    <h4 class="fieldset-legend">Items</h4>
</div>
<div class="grid np">
  <div class="hor-scroll">
    <table id="order_table" cellspacing="0" class="data order-tables">
	<thead>
            <tr class="headings">
		<th><?php echo $this->helper('sales')->__('Item ID') ?></th>
                <th>Quantity</th>
		<th><?php echo $this->helper('sales')->__('Product ID') ?></th>
		<th><?php echo $this->helper('sales')->__('Product SKU') ?></th>
		<th><?php echo $this->helper('sales')->__('Product Name') ?></th>
		<th><?php echo $this->helper('sales')->__('Product Weight (' . $this->getWeightUnits() . ')') ?></th>
		<th><?php echo $this->helper('sales')->__('Product Length (' . $this->getDimensionUnits() . ')') ?></th>
		<th><?php echo $this->helper('sales')->__('Product Width (' . $this->getDimensionUnits() . ')') ?></th>
		<th><?php echo $this->helper('sales')->__('Product Height (' . $this->getDimensionUnits() . ')') ?></th>
		<th><?php echo $this->helper('sales')->__('Product Volume (CU ' . $this->getDimensionUnits() . ')') ?></th>
                <th><?php echo $this->helper('sales')->__('Dangerous Goods') ?></th>
                <th><span class="nobr"><?php echo $this->helper('sales')->__('Item Status') ?></span></th>
            </tr>
        </thead>
        <?php $items = $this->getItems() ?>
        <?php   foreach($items as $item)
                {
                    $quantity_count[$item['product_id']][] = $item;
                }
                

        ?>
        <?php $i=0; foreach ($items as $item):?>
	    <input type="hidden" id="items[<?php echo $i; ?>][item_id]" name="items[<?php echo $i; ?>][item_id]" value="<?php echo $item['id']; ?>" />
            <tbody class="<?php echo $i%2?'even':'odd' ?>">
                <tr style="display: none;"id="product_row_<?php echo $i?>">

		    <td><input type="hidden" id="items_<?php echo $i; ?>_id" name="items[<?php echo $i; ?>][id]" value="<?php echo $i+1; ?>" /><div id="items_<?php echo $i; ?>_id_div"><strong><?php $init = $i+2 - count($quantity_count[$item['product_id']]); echo ($init == $i+1 ?  $i+1 : strval($init) . '-' . strval($i+1)); ?></strong></div></td>
                    <td><input type="hidden" id="items_<?php echo $i; ?>_quantity" name="items[<?php echo $i; ?>][quantity]" value="<?php echo count($quantity_count[$item['product_id']]); ?>" /><div id="items_<?php echo $i; ?>_quantity_div"><?php echo count($quantity_count[$item['product_id']]); ?></div></td>
		    <td><input type="hidden" id="items_<?php echo $i; ?>_product_id" name="items[<?php echo $i; ?>][product_id]" value="<?php echo $item['product_id']; ?>" /><div id="items_<?php echo $i; ?>_product_id_div"><?php echo $item['product_id']; ?></div></td>
		    <td><input type="hidden" id="items_<?php echo $i; ?>_sku" name="items[<?php echo $i; ?>][sku]" value="<?php echo $item['sku']; ?>" /><div id="items_<?php echo $i; ?>_sku_div"><?php echo $item['sku']; ?></div></td>
		    <td><input type="hidden" id="items_<?php echo $i; ?>_name" name="items[<?php echo $i; ?>][name]" value="<?php echo htmlspecialchars($item['name']); ?>" /><div id="items_<?php echo $i; ?>_name_div"><?php echo htmlspecialchars($item['name']); ?></div></td>
		    <td><input type="hidden" id="items_<?php echo $i; ?>_weight" name="items[<?php echo $i; ?>][weight]" value="<?php echo $item['weight']; ?>" /><div id="items_<?php echo $i; ?>_weight_div"><?php echo $item['weight']; ?></div></td>
		    <td><input type="hidden" id="items_<?php echo $i; ?>_length" name="items[<?php echo $i; ?>][length]" value="<?php echo $item['length']; ?>" /><div id="items_<?php echo $i; ?>_length_div"><?php if (!empty($item['length'])) { echo $item['length']; } else { echo '-'; } ?></div></td>
		    <td><input type="hidden" id="items_<?php echo $i; ?>_width" name="items[<?php echo $i; ?>][width]" value="<?php echo $item['width']; ?>" /><div id="items_<?php echo $i; ?>_width_div"><?php if (!empty($item['width']))	 { echo $item['width']; } else { echo '-'; } ?></div></td>
		    <td><input type="hidden" id="items_<?php echo $i; ?>_height" name="items[<?php echo $i; ?>][height]" value="<?php echo $item['height']; ?>" /><div id="items_<?php echo $i; ?>_height_div"><?php if (!empty($item['height'])) { echo $item['height']; } else { echo '-'; } ?></div></td>
		    <td><input type="hidden" id="items_<?php echo $i; ?>_volume" name="items[<?php echo $i; ?>][volume]" value="<?php echo $item['volume']; ?>" /><div id="items_<?php echo $i; ?>_volume_div"><?php if (!empty($item['volume'])) { echo $item['volume']; } else { echo '-'; } ?></div></td>
                    <td><input type="hidden" id="items_<?php echo $i; ?>_dangerous" name="items[<?php echo $i; ?>][dangerous]" value="<?php echo $item['dangerous']; ?>" /><div id="items_<?php echo $i; ?>_dangerous_div"><?php if ($item['dangerous']) { echo '&#10003'; } else { echo '-'; } ?></div></td>
		    <td><input type="hidden" id="items_<?php echo $i; ?>_status" name="items[<?php echo $i; ?>][status]" value="<?php echo $item['status']; ?>" /><div id="items_<?php echo $i; ?>_status_div"><?php echo $item['status']; ?></div></td>
		</tr>
            </tbody>
        <?php $i++; endforeach; ?>
    </table>
  </div>
</div>
<div class="clear"></div>
<br />
<div class="entry-edit-head">
    <h4 class="fieldset-legend">Estimated Packages</h4>
</div>
<div class="grid np">
  <div class="hor-scroll">
    <table cellspacing="0" class="data order-tables">
        <thead>
            <tr class="headings">
		<th><?php echo $this->helper('sales')->__('Package ID') ?></th>
		<th><?php echo $this->helper('sales')->__('Package Type') ?></th>
		<th><?php echo $this->helper('sales')->__('Package Items') ?></th>
		<th><?php echo $this->helper('sales')->__('Package Weight (' . $this->getWeightUnits() . ')') ?></th>
		<th><?php echo $this->helper('sales')->__('Package Length (' . $this->getDimensionUnits() . ')') ?></th>
		<th><?php echo $this->helper('sales')->__('Package Width (' . $this->getDimensionUnits() . ')') ?></th>
		<th><?php echo $this->helper('sales')->__('Package Height (' . $this->getDimensionUnits() . ')') ?></th>
		<th><?php echo $this->helper('sales')->__('Package Volume (CU ' . $this->getDimensionUnits() . ')') ?></th>
		<th><?php echo $this->helper('sales')->__('Max Package Volume (CU ' . $this->getDimensionUnits() . ')') ?></th>
		<th><?php echo $this->helper('sales')->__('Percentage Packed') ?></th>
            </tr>
        </thead>
        
        <?php $packages = $this->getPackages() ?>
        <?php $i=1; $z=0; foreach ($packages as $package):?>
            <tbody class="<?php echo $i%2?'even':'odd' ?>">
                <tr>
		    <td><?php echo $i; $i++; ?></td>
		    <td><?php echo Mage::helper('shipsync/packages')->getPackageName($package['type'])?></td>
		    <td><?php echo Mage::helper('shipsync/packages')->asRange($package['items'], 'item_number')?></td>
		    <td><?php echo $package['weight']; ?></td>
		    <td><?php echo $package['length']; ?></td>
		    <td><?php echo $package['width']; ?></td>
		    <td><?php echo $package['height']; ?></td>
		    <td><?php if (isset($package['volume'])) { echo $package['volume']; } ?></td>
		    <td><?php if (isset($package['max_volume'])) { echo $package['max_volume']; } else { echo '-'; } ?></td>
		    <td><?php if (isset($package['max_volume']) && isset($package['volume'])) { $q = round($package['volume']/$package['max_volume'], 2)*100; echo ($q == 0 ? 'undefined' : $q . '%'); } else { echo '100%'; } ?></td>
		</tr>
            </tbody>
        <?php endforeach; ?>
    </table>
  </div>
</div>
<div class="clear"></div>
<br />
<div class="entry-edit-head">
    <h4 class="fieldset-legend">Actual Shipment Request</h4>
</div>
<?php 

?>

<div class="grid np">
    <div class="hor-scroll">
	<table cellspacing="0" class="data order-tables" id="package_table">
	    <thead>
		<tr class="headings">
		    <th><?php echo $this->helper('sales')->__('Package ID') ?></th>
                    <th><?php echo $this->helper('sales')->__('Package Type') ?></th>
		    <th><?php echo $this->helper('sales')->__('Package Items') ?></th>
		    <th><?php echo $this->helper('sales')->__('Package Weight (' . $this->getWeightUnits() . ')') ?></th>                    
		    <th><?php echo $this->helper('sales')->__('Package Length (' . $this->getDimensionUnits() . ')') ?></th>
		    <th><?php echo $this->helper('sales')->__('Package Width (' . $this->getDimensionUnits() . ')') ?></th>
		    <th><?php echo $this->helper('sales')->__('Package Height (' . $this->getDimensionUnits() . ')') ?></th>
		    <th><?php echo $this->helper('sales')->__('Package Max Weight (' . $this->getWeightUnits() . ')') ?></th>
		</tr>
	    </thead>

	    <tbody class="<?php echo $i%2?'even':'odd' ?>" id="package_table_rows">
		<?php
                $i=0; $z=0;
                $this->getChild('shipsync_options')->setData('i', $i);
		$this->getChild('shipsync_options')->setData('z', $z);
                $this->getChild('shipsync_options')->setData('packages', $this->getPackages());
                echo $this->getChildHtml('shipsync_options');
                ?>
	        <input type="hidden" id="number_of_packages" value="<?php echo count($this->getPackages()) ?>" />
	    </tbody>
	</table>
    </div>
</div>
<br />
<div align="right">
    <button onclick="deletePackage();" class="none" type="button"><span><?php echo $this->__('Delete Package') ?></span></button>
    <button onclick="addPackage(optionsurl);" class="none" type="button"><span><?php echo $this->__('Add Package') ?></span></button>
</div>
<br />
<div align="right">
    <button onclick="updateShipment('<?php echo $rateUrl ?>');" class="none" type="button"><span>Update Shipment</span></button>
    <button onclick="editForm.submit(); Element.show('loading-mask');" class="scalable save" type="button"><span>Create shipment</span></button>
</div>
<script type="text/javascript">
var editForm = new varienForm('edit_form');
</script>
</form>

